/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaleminderitRouteImport } from './routes/faleminderit'
import { Route as PorositRouteImport } from './routes/porosit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleminderitRoute = FaleminderitRouteImport.update({
  id: '/faleminderit',
  path: '/faleminderit',
  getParentRoute: () => rootRouteImport,
} as any)
const PorositRoute = PorositRouteImport.update({
  id: '/porosit',
  path: '/porosit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faleminderit': typeof FaleminderitRoute
  '/porosit': typeof PorositRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faleminderit': typeof FaleminderitRoute
  '/porosit': typeof PorositRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faleminderit': typeof FaleminderitRoute
  '/porosit': typeof PorositRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faleminderit' | '/porosit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faleminderit' | '/porosit'
  id: '__root__' | '/' | '/faleminderit' | '/porosit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaleminderitRoute: typeof FaleminderitRoute
  PorositRoute: typeof PorositRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faleminderit': {
      id: '/faleminderit'
      path: '/faleminderit'
      fullPath: '/faleminderit'
      preLoaderRoute: typeof FaleminderitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porosit': {
      id: '/porosit'
      path: '/porosit'
      fullPath: '/porosit'
      preLoaderRoute: typeof PorositRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaleminderitRoute: FaleminderitRoute,
  PorositRoute: PorositRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
